### PR TITLE
(work in progress) MALED diarrhea sample details

### PR DESCRIPTION
**Pull request by wbazant**

### CODE REVIEW

**Comment by wbazant** [comment]
Still lots of terms aren't done - terms with dots are not in `ontologyMappingsMicrobiome.xml`:
[ISA-summary.txt](https://github.com/VEuPathDB/ApiCommonMetadataRepository/files/4042943/ISA-summary.txt)

Same but with some work in progress notes:
[MALED-diarrhea.ISA-summary.txt](https://github.com/VEuPathDB/ApiCommonMetadataRepository/files/4042941/MALED-diarrhea.ISA-summary.txt)

**Comment by wbazant** [comment]
I also need to fill in these so that cross-study queries work:

- done sample type - column header = ‘sample_type’ or ‘sampletype’
country
host common name -  (column header = ‘host_common_name’), 
‘body habitat’ (column header = ‘body_habitat’)
‘body site’ (column header, ‘host_body_site’ or ‘body_site), and ‘body product’ (column header, host_body_product or body_product). When the information is not in the dataset, we may obtain the information from the dataset name and sample type.

**Comment by zhengj2007** [comment]
> * done sample type - column header = ‘sample_type’ or ‘sampletype’
>   ‘body habitat’ (column header = ‘body_habitat’)
>   ‘body site’ (column header, ‘host_body_site’ or ‘body_site), and ‘body product’ (column header, host_body_product or body_product). When the information is not in the dataset, we may obtain the information from the dataset name and sample type.

Value for sample_type should be 'Stool' for consistency.

For 'Stool' sample, the values for body_habitat, body_product, and body_site should be:

body_habitat | body_product | body_site
-- | -- | --
Colon | UBERON:feces | Colon

For those mappings you have questions, it might be better to contact Danica to see whether they are same variables since she knows the MALED dataset very well.

It also needs to add column which header is 'env_feature', value is 'Human'.

Need consider to add column 'Child ID'.

Many columns are calculated results. The microbiomeDB.org site can analyze the data by selecting different observation period and other criteria. So, I am not sure whether we need to load those data such as 'Mean duration of campylobacter-negative diarrheal episodes in days', 'Mean duration of campylobacter-positive diarrheal episodes in days', 'Mean duration of diarrheal episodes in days'. Please contact Dan for it.

**Comment by wbazant** [comment]
Added  body_habitat=Colon body_product=UBERON:feces body_site=colon env_feature=Human host_common_name=Human sample_type=Stool.

These terms still don't have mapping:
```
  ...family member: child
  ...sequencing method: Illumina MiSeq
  ...born stunted: 'no, yes'
  ...breastfeeding category: 'Exclusive, Partial, Predominant, Weaned'
  ...burden group for campylobacter: 'NA, high, low, mid'
  ...burden group for eaec: 'NA, high, low, mid'
  ...burden group for giardia: 'NA, high, low, mid'
  ...burden group for norovirus: 'NA, high, low, mid'
  ...in subcohort with no diarrhea for 30 days: 'no, yes'
  ...outlier removed from models: 'no, yes'
  ...severely stunted at sampling: 'no, yes'
  ...stunted 3 months after sampling: 'NA, no, yes'
  ...stunted at sampling: 'no, yes'
  ...stunting category: 'NS/NS, NS/S, NS/Sv, S/NS, S/S, S/Sv'
  ...days on antibiotics: 0 to 167
  ...days since last diarrheal episode: 'NA, 0 to 592'
  ...laz 1 month after sampling: 'NA, -4.37 to 1.63'
  ...laz 3 months after sampling: 'NA, -4.8 to 1.41'
  ...laz at enrollment: -4.61 to 1.97
  ...laz at sampling: -4.8 to 1.3
  ...mean daily feeds at breast: 0 to 33.811
  ...mean duration of campylobacter-negative diarrheal episodes in days: 'NA, 1 to 18.333'
  ...mean duration of campylobacter-positive diarrheal episodes in days: 'NA, 1 to 28'
  ...mean duration of diarrheal episodes in days: 'NA, 0 to 28'
  ...mean severity of campylobacter-negative diarrheal episodes: 'NA, 0 to 9'
  ...mean severity of campylobacter-positive diarrheal episodes: 'NA, 0 to 11'
  ...mean severity of diarrheal episodes: 'NA, 0 to 9'
  ...number of campylobacter-negative diarrheal episodes: 'NA, 0 to 27'
  ...number of campylobacter-positive diarrheal episodes: 'NA, 0 to 15'
  ...number of diarrheal episodes: 0 to 28
  ...pathogens per month: 0 to 1.875
  ...pathogens per month excluding campylobacter: 0 to 1.75
  ...percentage of diarrheal samples positive for campylobacter: 'NA, 0 to 100'
  ...percentage of surveillance samples positive for pathogens excluding campylobacter: 0 to 100
  ...percentage of surveillance stools positive for campylobacter: 'NA, 0 to 92.308'
```

**Comment by wbazant** [comment]
These are left:

```
  ...family member: child
  ...born stunted: 'no, yes'
  ...breastfeeding category: 'Exclusive, Partial, Predominant, Weaned'
  ...severely stunted at sampling: 'no, yes'
  ...stunted 3 months after sampling: 'NA, no, yes'
  ...stunted at sampling: 'no, yes'
  ...days on antibiotics: 0 to 167
  ...days since last diarrheal episode: 'NA, 0 to 592'
  ...laz 1 month after sampling: 'NA, -4.37 to 1.63'
  ...laz 3 months after sampling: 'NA, -4.8 to 1.41'
  ...laz at enrollment: -4.61 to 1.97
  ...laz at sampling: -4.8 to 1.3
  ...mean daily feeds at breast: 0 to 33.811
  ...mean duration of campylobacter-negative diarrheal episodes in days: 'NA, 1 to 18.333'
  ...mean duration of campylobacter-positive diarrheal episodes in days: 'NA, 1 to 28'
  ...mean duration of diarrheal episodes in days: 'NA, 0 to 28'
  ...mean severity of campylobacter-negative diarrheal episodes: 'NA, 0 to 9'
  ...mean severity of campylobacter-positive diarrheal episodes: 'NA, 0 to 11'
  ...mean severity of diarrheal episodes: 'NA, 0 to 9'
  ...number of campylobacter-negative diarrheal episodes: 'NA, 0 to 27'
  ...number of campylobacter-positive diarrheal episodes: 'NA, 0 to 15'
  ...number of diarrheal episodes: 0 to 28
  ...pathogens per month: 0 to 1.875
  ...pathogens per month excluding campylobacter: 0 to 1.75
  ...percentage of diarrheal samples positive for campylobacter: 'NA, 0 to 100'
  ...percentage of surveillance samples positive for pathogens excluding campylobacter: 0 to 100
  ...percentage of surveillance stools positive for campylobacter: 'NA, 0 to 92.308'
```

They are definitely authors' summaries of observations. This is from the paper:
https://academic.oup.com/view-large/figure/186361663/ciz905f0001.jpg
`breastfeeding category` is, I think, derived from "mean daily feeds at breast" by the authors.

The paper says the data about campylobacter and `pathogens per month` is derived from microbiological observations.

**Comment by wbazant** [comment]
Formatted the metadata as  https://gist.github.com/wbazant/68c8fb547fe4a66ae18451ca726b7474 with Jie, she's now adding it to the ontology

**Pull request merged**
